### ISSUE TITLE
Release? 

### ISSUE THREAD

**Issue by jensens** [zopefoundation/zope.pytestlayer#49]
We have the problem in Plone that we would need a first release. We currently are sprinting in Bonn at Beethoven-Sprint , so it blocks us a bit, mainly because of missing Python 3.12 support in the old gocept.pytestlayer.
So 
- What is needed? We can try to fix/enhance this.
- @icemac can you do this or may @mauritsvanrees step in here or anyone else?

Thanks!

**Comment by icemac** [comment]
I am on it.

**Comment by icemac** [comment]
I just released https://pypi.org/project/zope.pytestlayer/8.2/

CC @ericof @mauritsvanrees

**Comment by ericof** [comment]
Thank you @icemac!
